export const PROCESS_CHECKOUT = 'PROCESS_CHECKOUT';
export const GENERATE_TOKEN_CHECKOUT = 'GENERATE_TOKEN_CHECKOUT';
export const GET_SHIPPING_OPTION = 'GET_SHIPPING_OPTION'
export const REMOVE_SHIPPING_OPTIONS = 'REMOVE_SHIPPING_OPTIONS';
export const UPDATE_CHECKOUT_LIVE_OBJECT = 'UPDATE_CHECKOUT_LIVE_OBJECT';
export const ABORT_CHECKOUT = 'ABORT_CHECKOUT';
export const CAPTURE_ORDER_SUCCESS = 'CAPTURE_ORDER_SUCCESS';
